# Generated by Django 5.2.8 on 2025-11-16 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ourguards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ourguards_person', models.CharField(max_length=150)),
                ('Ourguards_post', models.CharField(blank=True, max_length=150)),
                ('Ourguards_img', models.ImageField(blank=True, null=True, upload_to='ourguards/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
                ('Ourguards_file', models.FileField(blank=True, null=True, upload_to='ourguards/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
