# Generated by ChatGPT to add attachment field to Contact
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactFrom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='attachment',
            field=models.FileField(upload_to='contacts/', null=True, blank=True),
        ),
    ]
